### ISSUE TITLE
[RFC] flagging components experimental/unstable

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1137]
### Summary

Currently, experimental/unstable components are only labeled as such in the storybook. Consumers are not notified in any way that a component they are using is subject to change outside of semver.

How can we communicate this expectation of instability to consumers without them having to know to look at the storybook?

### Initial proposal

I think there are two primary ways we can provide the affordance of instability to consumers:

1. Name components with a prefix of `Unstable`. This will make it hyper clear to consumers on import and usage that the component is experimental.
   - When an unstable component is deemed stable, it would be renamed to remove the `Unstable` prefix. 
   - We could attempt to provide a codemod/script for consumers to run on their codebase that would re-write their imports for them, though a 'find all and replace' in a code editor during upgrade is just as easy.
2. Provide a [`deprecate()` type of message](https://github.com/IBM/carbon-addons-iot-react/blob/master/src/internal/deprecate.js) in the console when a component is used that is unstable.
   - This is sort of annoying, but would completely avoid the import rewrites.
   - Carbon took this route with the UIShell before it 

@stuckless @scottdickerson @sstone2423  @bryancboyd @jm986 which would you prefer here? Any alternative ideas?

**Comment by sstone2423** [comment]
I'd vote for the Unstable prefix. It might also help to add a disclaimer to the stories above the preview. I tend to skim over that Experimental label

**Comment by scottdickerson** [comment]
To be honest, I'm just okay with having a bolded comment in the Storybook, I think that's the starting point for interacting with these widgets @tay1orjones

**Comment by stuckless** [comment]
In our storybook we use Nuke symbol to denote components that are are not fully vetted.  ie, these component might still need UI work, etc.  Checkmark, means they are good.

![image](https://user-images.githubusercontent.com/1056553/80752053-e400c680-8af8-11ea-9efe-4e39f94c7ff3.png)

Now along the lines of the `deprecate()`, you could use an `unstable()` and give an unstable message vs decrecation since they mean 2 different things.  In this way, once you move from Unstable to Stable you just remove the `unstable()` messaging, and the downstream consumers don't need to update anything in their code.

**Comment by sstone2423** [comment]
I'd agree that putting it at the storybook level should be informative enough too. Its hard to imagine that developers are using these components without looking at Storybook

**Comment by stuckless** [comment]
@sstone2423 That was my question to Taylor (in another thread) as well.  ie, What does it mean to be experimental.  Is is that the component isn't complete (lacks testing, lacks styling, something else).  I'm not a fan of using experimental simply because we want to defer the technical debt of a component.  If a component is used in a product and that product is released to customer, it's not experimental (to me).  So I think there are 2 things to cover... 
1) what does is mean when we say experimental (ie, the criteria)
2) how to let others know that it is experimental

As for storybook... while I do go there to visually look at a component... I almost never use it for information.  I have to have the iot components checked out and read the sources for most things that I want to do with a table or dashboard :(  (Our storybook isn't much better, but, it's less of an issue since storybook is not the source of documentation for our app developers)

**Comment by sstone2423** [comment]
From my understanding of our library, it means it lacks testing and could have large changes (even rewrites) without the semver notices (major, minor, etc). I also assume that all new components are put into that category, but its also a little bit confusing as to the guidelines as to how a component becomes "stable". Is there a certain amount of time that needs to elapse, or a certain amount of test coverage?

**Comment by tay1orjones** [comment]
Yeah, we can't solely rely on the storybook. It has to be present somewhere in the published code bundle that we provide to the consuming application. A console message seems appropriate. The storybook should definitely be improved as well - that example from react is 💯 

"Experimental" needs to be codified. The intent was born from the need of a product team to rapidly iterate within this codebase leading up to a release, deferring technical debt until there is a reasonable expectation of stability defined by it being shipped in a product release.

---

I think we can move forward with the following:
### Codify `Experimental`
  - [ ] Document the definition and process to `stable` in new `/docs/experimental.md`
    - Definition
      - component has not been shipped in a product
      - the sponsoring/consuming application expects potential changes in a short time frame (<3 mo)
      - inherently low test coverage due to shifting api/styles/markup/etc
      - low/no documentation
      - not the default for all new components - most will have reqs fully fleshed out between the design team, core PAL team, and consuming/sponsoring product team
    - Candidate for stability is generally defined by 2-3 of the following (ideally _all_ of the following): 
      - component is used in product code
      - hasn't had any recent changes that would be defined as "breaking/major"
      - the team utilizing component in a product doesn't expect changes in the near future (<3mo)
      - no outstanding major additional requirements
      - original contributor has no outstanding requirements/issues
      - ideally has shipped in product code to customers.
    - Move to `stable` _requires_: 
      - standard test coverage threshold (80% right now I believe)
      - documentation in storybook
      - i18n, no major a11y concerns, meets any other acceptance criteria we define, #1024 

### Notify consumers of `Experimental` components
- [ ] Update storybook welcome to link to the full documentation
  - [ ] Experimental components should have a 'this component is experimental` notice in the story, with a link to the full documentation
- [ ] Add console messages in dev for components marked experimental/unstable, link to the full documentation
- [ ] remove the unstable prefix from any components that have it

**Comment by tay1orjones** [comment]
> I would just vote that we use `console.warn` instead of the `console.error` that our warning tool uses

[There is some discussion behind the usage of console.error](https://www.npmjs.com/package/warning#faq-read-before-opening-an-issue) in the `warning` package to provide native stack traces.

For now let's continue to use `warning`. The toolchain is set up to automatically remove the logs in non-dev environments.

**Comment by tay1orjones** [comment]
The `babel-plugin-dev-expression` plugin we use to strip the warnings from production [only looks at the name of the function](
https://github.com/4Catalyzer/babel-plugin-dev-expression/blob/1a4f531cef676e613eed38cc9f6f560f759d560d/dev-expression.js#L103) to determine if it should be stripped out.

So in theory we could create our own `warning()` helper that wraps the `warning` package under some logic to use console.error or console.warn in certain situations.

**Comment by davidicus** [comment]
Experimental documentation was added to the repo in February from [this](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2064) PR
