### ISSUE TITLE
[Dropdown] with icon selection buttons

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1259]
### Summary

This contribution enables users to quickly and easily pick between options that are visually recognisable rather than necessarily recognisable by name. Specifically when picking between chart types.

**Additional context**
Design context from the internal issue [pal-tracking#174](https://github.ibm.com/watson-iot/pal-tracking/issues/174):

> https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319194959
> 
> - This dropdown presents itself mostly as a regular dropdown before interaction, with the notable exception of an icon in the value along with text:
> 
> - Once opened, this dropdown supplies a space for custom content. The desired example would be selection icon buttons #153 
> - In this case, the selected button will appear both as an icon and text value in the dropdown, but also in the 'selected state' in the dropdowns suggestion box.
> 
> - When a new value is selected, the icon and text in the main field updates.
> 
> 
> **Inspiration from other products**
> This is used in the EDS 'analysis' UX pattern (no consumers presently): https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319195042
> Image: 
> ![image](https://media.github.ibm.com/user/684/files/d77a4680-200d-11ea-9e7b-a031efbb978c)

**Comment by tay1orjones** [comment]
High level implementation notes:

- use Carbon's ListBox and sub components
- provide itemToElement function that converts items object to `<Button hasIconOnly/>`
- onChange handler prop
- `footer` slot prop (to support the bottom custom content)
- placing an icon in select box has been implemented similarly in the TableViewsDropdown and could likely be reused @bjornalm

**Comment by ajnaddell** [comment]
@CynZhang - is this still needed with the new design of the floating pallet?

**Comment by CynZhang** [comment]
@ajnaddell yes, is a value added item for the dashboard config pane to switch chart type.

**Comment by dianatran18** [comment]
I chatted with @CynZhang and #1373 can be used in a few areas for Monitor and for the new dashboard configuration work, so I'm thinking we might not need to support this option, as the other one is sufficient.

I have questions/concerns about this dropdown:
- is the width fixed so you can only have 3 tiles going across? can there be more/less?
- when hovering over the tile, having a tooltip to show the name of the icon can get in the way and makes the dropdown become super complex, but without the label the icons alone might not be clear

The closed state is the same as #1373, and the other option has the text label paired with the icon so that is overall easier to understand and use.
