### ISSUE TITLE
[Table] reorder rows

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1272]
### Summary

Sometimes the particular order of rows in a table is important (eg for certain schemas or for priority of work), this contribution intends to allow users to reorder rows in the table to represent their desired ordering.

**Additional context**
From 
[Internal Watson-IoT/pal-tracking#160](https://github.ibm.com/Watson-IoT/pal-tracking/issues/160)

> An icon is added to the toolbar which looks like the column picker on its side to represent picking rows. Upon selection, the table enters a special reordering state with grab handles rendered on the left most part of the row, with a save/cancel button pairing pushing the tools in the toolbar left until the state is saved or cancelled.
> ![image](https://media.github.ibm.com/user/684/files/cd7ecf00-1c2c-11ea-882e-43c8463942dc)
>

**Comment by tay1orjones** [comment]
One potential blocker here is that the react-dnd (drag and drop) hook requires a ref to the root element. Carbon doesn't forward a ref from the TableRow. A couple options:

1. Submit an enhancement to Carbon to use fowardRef in the TableRow, wait for that to be published, then implement this feature
1. Reimplement the TableRow by copy/pasting the source from Carbon, submit the forwardRef enhancement, implement the forwardRef in our copy/paste, develop this feature, and then refactor to remove the copy/paste version of TableRow once the fix is published.f

If this is not a top priority item, I'd prefer us to do option 1 and wait to implement this after we've got the fix published in Carbon. Option 2 is a lot of overhead that we should only take on if it's imperative we develop this asap.

**Comment by tay1orjones** [comment]
`List` does not use the Table under the hood, so there isn't a dependency here. We can deliver this independent of the List reordering of rows in #1344

**Comment by stuckless** [comment]
@tay1orjones Have you given any thought to the technical implementation once the dnd is resolved.  ie, What happens when drage/drop.  Do I get a callback with a reorder request and something would then need to reorder the items and then send those items back to the table?  Does the table just manage the state of the reorder, but forwards the action off as FYI (ie, like column resizing).

**Comment by bjornalm** [comment]
> @tay1orjones Have you given any thought to the technical implementation once the dnd is resolved. ie, What happens when drage/drop. Do I get a callback with a reorder request and something would then need to reorder the items and then send those items back to the table? Does the table just manage the state of the reorder, but forwards the action off as FYI 
 (ie, like column resizing).

This makes me curious. Is this a pure UI thing and the the row ordering will become an explicit metadata property separated from the actual data? If so, how is it combined with sorting and pagination? The reason for adding reordering functionality mentions certain schemas, how does schemas fit into this?

My two cents on the state management since I noticed that the column resize was mentioned: Having the non stateful table managing the state of the column widths for the column resize was probably not the best approach because it opens up for a lot of additional complexity when the application still needs to be able to set some specific column widths after init. So, learning from that, if we expect that the application at some point will load some pre-defined row order the row order state should probably not be managed in the normal table (but possibly in the stateful table).

**Comment by stuckless** [comment]
@bjornalm That's a good point about sorting.   Does it make sense that you can sort AND reorder, and if you did, what is the expectation here... is an application supposed to sort and remember the rearranged rows that are no longer in sort order?  Granted, if the act of reordering is meant to be a data editing feature, then, I can see sorting and reordering both working together.  ie, data is sorted by priority, you drag a row and drop it, and the drop handler re-calculates a new priority based on the drop location, updates the data, and the table is in sort order.  But, this is complicated, and not sure it is the intention of re-ordering.

**Comment by tay1orjones** [comment]
Yeah these are great questions - I'm not sure on the answer. There's also the question of if the table "freezes" and isn't intractable while in "dnd mode" 

We're just beginning to look at this and probably need to have a roundtable for both for this and also the smaller related issue of reordering list rows #1344 
 
@amymillett @lukefirth @dianatran18 a lot of this is UX related and would make sense to be defined from a design/UX perspective. Narrowing down the intent will help define a clearer path of implementation. I also would like to hear from the product teams requesting this feature and what they're expecting in regards to the above items. Sorting, filtering, pagination - how all of these intend to work with row reordering.

**Comment by ajnaddell** [comment]
@scottdickerson - Monitor was tagged for this. Do you know we would need this as opposed to List card reorder? I am thinking about Hierarchy theme work.

**Comment by davidicus** [comment]
No longer valid. If someone still has a use case for this please reach out to design and we can reopen.
