### ISSUE TITLE
[table] manage existing views modal

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1308]
### Summary
As part of #1210 we need to create a modal that lets the user manage existing views.

**Additional context**
The modal would look like this:
![image](https://user-images.githubusercontent.com/5167091/84676232-894aef00-af2d-11ea-8e0d-0abd4927060b.png)

- search name of existing views
- filter on public true/false
- list views displaying (name, description, private/public, default/not default
- trigger "view edit mode"
- trigger view deletion

**Questions**
@davidicus @lukefirth @amymillett
1. Do we need to support server search/filtering, i.e. some sort of async update that might take time?
2. How does a long list look like? e.g. use scrolling? load from server while scrolling? pagination?
3. Editing a view will open up the same modal as the "Save view" but pre filled with the name etc . So I assume that the "Manage Views Modal" will close, but what happens after the view was saved. Does the "Manage Views Modal" reopen or stay closed?
4. What happens when the user clicks on delete, should there not be a warning before a destructive action? Or should an undo option be presented in a toast or something?
5. Are the colors correct? The default modal background is white and the default search field is gray, in this design it is the other way around. 
6. Should all views in the list always be editable and deletable or should that be a property of the list item itself?

**Comment by davidicus** [comment]
Pushing this to sprint 53 since @bjornalm is out this week

**Comment by lukefirth** [comment]
**1. Do we need to support server search/filtering, i.e. some sort of async update that might take time?**
- I think for this one, yes.

---

**2. How does a long list look like? e.g. use scrolling? load from server while scrolling?**
- Let us scroll and then use the list pagination at 10 items. 

----


**3. Editing a view will open up the same modal as the "Save view" but pre filled with the name etc . So I assume that the "Manage Views Modal" will close, but what happens after the view was saved. Does the "Manage Views Modal" reopen or stay closed?**
- Lets let it close. I do not think we have a usecase 

------

**4. What happens when the user clicks on delete, should there not be a warning before a destructive action? Or should an undo option be presented in a toast or something?**
- Agreed, confirmation dialog.

----

**5. Are the colors correct? The default modal background is white and the default search field is gray, in this design it is the other way around.** 
- This is a great point, I'll lean on @amymillett for this, but there is also actually a [conversation on this topic in the Carbon Slack channel today](https://ibm-ai-apps.slack.com/archives/C0M053VPT/p1595532677393000). I may be proven wrong, but I think in this case it would actually be a white modal, white a white table overlaid and bleeding to the edge.

-------

**6. Should all views in the list always be editable and deletable or should that be a property of the list item itself?**
- I'd play it safe here and allow it to be a property. I have certainly seen Maximo use cases at least where they have some views that are owned by others that you cannot change.

**Comment by bjornalm** [comment]
@lukefirth The Modal component (I'm using the ComposedModal) adjusts it's height depending on the content and the available screen space which makes sense for content where the height doesn't change once the modal is opened. But in this case where we filter the content the height of the modal will change while the user types in the search field depending on the number of rows that are returned. The easiest solution would be to have a fixed height of the modal content, would you agree to that and what height should we use in that case?

**Comment by tay1orjones** [comment]
@dianatran18 would you have any insight for the above question from @bjornalm ?

**Comment by dianatran18** [comment]
Let's stick with a fixed height. I think it would be too jarring for the modal to be jumping in size as the user starts to filter down the list.
