### ISSUE TITLE
[Component Proposal] Marketplace FeaturedProductTile

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1441]
From @lukefirth via [Internal Watson-IoT/pal-tracking#133](https://github.ibm.com/Watson-IoT/pal-tracking/issues/133)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> A compound component for showing a single 'featured' resource inside a tile catalog pattern.
> 
> Alone, it looks like one white tile, with title, subtitle, description, link (read more), primary button, custom footer content (in this case $100) and a large left aligned image thumbnail:
> ![image](https://media.github.ibm.com/user/684/files/fd14d500-1b61-11ea-837c-951f98f4848a)
> 
> **It can be found as the first example in this link:**
> https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743

**Comment by ajnaddell** [comment]
@lukefirth - what application needs this? Just trying to understand priority.

**Comment by lukefirth** [comment]
@ajnaddell If it wasn't tagged with a team that needs it, then no teams do as far as I am aware. It's here because we were directed to track and eventually implement everything that was an item from the original EDS. Many of them like this have sat on the shelf since that time, until a team raises that a need for it. 👍

**Comment by davidicus** [comment]
no longer valid. closing.
