### ISSUE TITLE
[FileDrop] accept prop not working for drag-and-drop

### ISSUE THREAD

**Issue by JoelArmendariz** [carbon-design-system/carbon-addons-iot-react#1453]
### Describe the bug

The `accept` prop in `FileDrop` is not validating the file type for 'drag-and-drop' style file imports.
The 'browse' variant properly validates.

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-filedrop--accept-json
2. Import a file that's not .json
3. See that it successfully uploads

### Expected behavior

It should only allow files of the types specified in the `accept` prop.

![Screen Shot 2020-07-30 at 1 51 11 PM](https://user-images.githubusercontent.com/53092833/88962245-c9f79100-d26b-11ea-9b0b-c794b866b3f0.png)

**Comment by tay1orjones** [comment]
I would recommend refactoring to use [FileUploader](https://carbon-addons-iot-react.com/?path=/story/fileuploader--drag-and-drop-upload-container-example-application) instead of FileDrop. FileDrop was created before FileUploader (from Carbon) supported drag and drop. Now that FileUploader has drag and drop support, is there anything preventing you from using FileUploader instead of FileDrop? 

We absolutely can keep it around and fix this specific issue if needed, but so far we haven't heard anything preventing deprecating FileDrop, https://github.com/carbon-design-system/carbon-addons-iot-react/issues/611

**Comment by JordanWSmith15** [comment]
Won't fix. Component will soon be deprecated as it should be replaced by Carbon version https://carbon-addons-iot-react.com/?path=/story/fileuploader--drag-and-drop-upload-container-example-application
