### ISSUE TITLE
[Table] When all the rows are selected through prop, the 'AllSelected' checkbox isn't checked

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1464]
### Describe the bug
When all the rows of the table are selected through view.table.selectedIds prop, the 'AllSelected' checkbox isn't automatically checked 

Here's a table where I pass the view.table.selectedIds prop as an array that matches the length the entire table data, but the top checkbox shows unselected

![image](https://user-images.githubusercontent.com/6663002/89462480-12fb8980-d733-11ea-8db4-435f954ace7a.png)

### To Reproduce

Simply instantiate a table with props where all the selectedIds that are selectable are selected

```
<CommonTable
        {...this.props}
        lightweight
        columns={tableColumns}
        data={tableData}
        options={{
          hasRowSelection: 'multi',
        }}
        view={{
          table: { selectedIds: selectedDimensions },
        }}
        actions={{
          table: { onRowSelected: onSelect, onSelectAll },
        }}
      />
```

**Comment by scottdickerson** [comment]
Can workaround this by passing this in the view

```
 view={{
          table: {
            selectedIds: selectedDimensions,
            isSelectAllSelected: selectedDimensions.length === tableData.length,
            isSelectAllIndeterminate:
              selectedDimensions.length > 0 && selectedDimensions.length !== tableData.length,
          },
        }}
```

**Comment by bjornalm** [comment]
Is this really is a bug? Since the app actually controls the `view.table.isSelectAllSelected` like the suggested workaround shows I'm not sure it makes sense to handle this value automatically. With this fix implemented, what is the use case of the `view.table.isSelectAllSelected` (and possibly `view.table.isSelectAllIndeterminate`) if those values are automatically calculated? At some point I assume there was a decision to add these props to the view for the normal table instead of calculating them like the StatefulTable does. So I think we should go with either

a) Don't add this fix
b) Add this fix and if we don't have a use case for overriding the automatically calculated props `view.table.isSelectAllSelected` and `view.table.isSelectAllIndeterminate` then we should probably deprecate them.
