### ISSUE TITLE
[Table] table loses search on delete row/tableData update

### ISSUE THREAD

**Issue by JoelArmendariz** [carbon-design-system/carbon-addons-iot-react#1488]
### Describe the bug

When a search is applied, followed by a row action to change the table data (ie: removing/deleting a row), the table loses the search filter, while keeping the search value in the input field.

### To Reproduce

I was able to recreate this issue by updating the `with pre-filled search` Table story to be populated by data held in state.
If you add a row action that manipulates that state (in my case, to remove a row via `.slice()`) and invoke the row action the table loses its filter while still showing the search value in the input field.

### Expected behavior

The table should not lose its filter.

### Environment/versions:

- OS: [MacOS]
- Browser: [Firefox]

Before clicking the row action:
![Screen Shot 2020-08-12 at 10 57 00 AM](https://user-images.githubusercontent.com/53092833/90038144-aa5c6180-dc8a-11ea-9f2a-9ad9f5e8423b.png)

After clicking the row action:
![Screen Shot 2020-08-12 at 10 57 15 AM](https://user-images.githubusercontent.com/53092833/90038160-b2b49c80-dc8a-11ea-909d-21ce4c2eadde.png)

**Comment by bjornalm** [comment]
This issue was fixed when we introduced the user view management functionality. For that feature we fixed several problems related to updating views and data externally, but in order not to break existing functionality it was (and is) conditionally activated using the prop `table.options.hasUserViewManagement`. So if you set that prop to be `true` your problem should be solved.

**Comment by JordanWSmith15** [comment]
@JoelArmendariz Closing this, as it appears fixed. If you still encounter it, please re-open and notify me
