### ISSUE TITLE
[Tab] property tabIndex is not applied

### ISSUE THREAD

**Issue by daumann** [carbon-design-system/carbon-addons-iot-react#1533]
### Describe the bug

The tabIndex property of the <Tab> component is seemingly ignored.

### To Reproduce

`<Tabs>
                <Tab tabIndex={0}>
`

generate

`<li role="tab" tabindex="-1" class="bx--tabs__nav-item" aria-selected="false" aria-disabled="false" aria-controls="tab-2__panel" style="padding-left: 0px; padding-right: 0px;"><a id="tab-2" class="bx--tabs__nav-link" href="#" tabindex="-1">Add-ons (1)</a></li>`

as HTML

All selected Tabs are tabindex 0 while all non selected tabs are -1, no matter what you supplied as the property value.

**Comment by davidicus** [comment]
Hi @dakahn. I believe they are all `-1` because the `Tab` components are part of a tab group. So you would not "tab" to each `Tab` component but "tab" once into the group and use the arrow keys to navigate between them. The prop you are using it meant to set the active `Tab`'s tabindex. In your example the `0` you are setting is being applied to the active tab as expected. I hope that makes sense. 

Is there something specific you are trying to achieve?

**Comment by dakahn** [comment]
I think I was mistakenly tagged, but yeah @davidicus has the right idea. Tab to the tab group and arrow keys to switch tabs 🏄🏽

**Comment by bjornalm** [comment]
@daumann ^
