### ISSUE TITLE
ComposedModal: Unable to close the modal using the close icon as onClose event is hardcoded in the component.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#1550]
Hello Team,

I am trying to implement a modal using ComposedModal component, but clicking on close icon on the modal header doesn't close the modal. I found that the onClose prop is set to false in the component code. 

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22093326/91528743-ad5f7f00-e925-11ea-827d-29f177d99181.png">

I am using carbon-addons-iot-react: 2.77.3

**Comment by tay1orjones** [comment]
Yes, the `onClose` prop on `CarbonComposedModal` always returns false so that modals aren't closed when clicked outside of the modal bounds.

https://github.com/carbon-design-system/carbon-addons-iot-react/blob/6226ef99ae68e68ec080191d5acb54cc26d6e0df/src/components/ComposedModal/ComposedModal.jsx#L128-L129

The `onClose` callback is still called when the header is interacted with:
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/6226ef99ae68e68ec080191d5acb54cc26d6e0df/src/components/ComposedModal/ComposedModal.jsx#L177-L183
and also when the cancel button is clicked:
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/6226ef99ae68e68ec080191d5acb54cc26d6e0df/src/components/ComposedModal/ComposedModal.jsx#L211-L213

The `open` prop should control if the modal is open or closed. In the `onClose` function you can set some local state in your wrapper/containing component toggle the `open` prop to `false` which should close the modal. Try this out and let us know how it goes. Feel free to reopen this issue if you run into problems.
