### ISSUE TITLE
[Table] Show column totals for all data in a table

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#1580]
### Summary
NOTE: Pending PAL Design review.  Not yet ready for development.
A user can see the total of all the values in a table column (includes values on all pages).  A user can choose to show or hide the totals row.

**Additional context**
Proposed approach for showing totals
Interactive ptype: https://f0uxik.axshare.com/
![image.png](https://images.zenhubusercontent.com/5f2aaf1e3c146556652ed02e/27fd4188-35d2-4c92-9d7d-e9bf6786e95c)
![image.png](https://images.zenhubusercontent.com/5f2aaf1e3c146556652ed02e/e4617a94-8a7c-4146-aebc-4e26b63eae63)

- Option to show / hide total row - if user option, accessible from the overflow menu.
- Option to display the word "totals" - if shown, first column is not totaled.
- Totals row is frozen, rows scroll under it
- Thicker line to separate totals row from regular rows
- Totals in bold
- Numeric, non-date columns are totaled
- When user exports table data, totals are included

Question:
- Would the app team be able to choose which columns are totaled?  We would probably want a generic option in some cases, but select specific columns in other cases.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

This is scheduled ~~as a stretch goal for the October Health release.  It's more likely~~ to be part of the Jan release of Health.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by KarenGski** [comment]
@dianatran18 I opened this issue to track the totals showing in tables request.  Adding the screenshot you shared:

![image.png](https://images.zenhubusercontent.com/5f2aaf1e3c146556652ed02e/ccc21117-10bc-46c6-a7fa-6a1446fe1b8c)

How do we go about settling this design issue?  I believe we would need this finalized in the next few days if we want any chance of getting it into our October release.

**Comment by msperli** [comment]
Small design update:
The text style and color should match that of the header titles.
Semibold + #161616

![image.png](https://images.zenhubusercontent.com/5f5bcc336c2a77d2868653ab/c9748aa0-8fa5-4537-8e24-b5eba0c913b0)

**Comment by KarenGski** [comment]
@davidicus I just found out that we are postponing the work that requires this feature from the October release to the January release.

**Comment by dianatran18** [comment]
@KarenGski can we open up an issue for this on the [pal repo](https://github.ibm.com/ai-applications/pal/issues) so we can track the design pattern on this, now that it's being postponed

**Comment by tay1orjones** [comment]
Going to put this on hold until the design is finalized

**Comment by KarenGski** [comment]
@dianatran18 I opened an item in the design PAL https://github.ibm.com/ai-applications/pal/issues/484
FYI @msperli

**Comment by bjornalm** [comment]
How do we handle the word "Totals" in the first column if the first column is a checkbox column?
![image](https://user-images.githubusercontent.com/5167091/97555391-5b47e200-19d8-11eb-88d5-6cd7457bff43.png)

**Comment by bjornalm** [comment]
Some thoughts regarding the implementation:
- This functionality will only work for tables that load all the pages at ones, i.e. not for tables with async loading of data during pagination. 
- With very little extra effort we can make this more flexible by allowing more then just a total (SUM) function.
- There will be a new options prop called `hasAggregations` that controls the visibility of the row with aggregation values. To allow the end user to show/hide this row the app can use the existing `customToolbarContent` and insert an overflow menu with items to externally manage the state of the hasAggregations prop.
- If this row is placed at the top of the table then stickyness can and probably should be achieved with the general sticky header function, since having this row sticky and the column headers scroll would be weird.
- We probably want the app to be able to control the formatting of the values and possibly also the type of aggregation (perhaps someone wants to show the average instead of the sum). This should then be controllable per column, e.g via e new view prop called `aggregations`:

```
    aggregations: PropTypes.shape({
      rowLabel: PropTypes.string,
      columns: PropTypes.arrayOf(
        PropTypes.shape({
          /** id of the column that should have its values aggregated */
          id: PropTypes.string.isRequired,
          /** String to be used as title attribute for the element holding the value */
          title: PropTypes.string,
          /** function that will receive an array of values and returns an aggregated value, defaults to a SUM function */
          aggregationFunction: PropTypes.func,
          /** custom formatter that takes the value (a number) and returns a string to be displayed */
          valueFormatter: PropTypes.func,
        })
      )
```

**Comment by dianatran18** [comment]
We came to the same conclusion on the [design side](https://github.ibm.com/ai-applications/pal/issues/484) where it makes more sense to have a lazy load (instead of pagination) so it's clear to users that it's the total of the full set of data. I wasn't sure if that was doable or not. 

<img width="1005" alt="Screen Shot 2020-10-29 at 12 16 17 PM" src="https://user-images.githubusercontent.com/43549567/97601450-8fbf9c00-19e0-11eb-947e-3c8806467bbf.png">

Regarding this question:

> How do we handle the word "Totals" in the first column if the first column is a checkbox column?

Is it possible to know if there are checkboxes or not on the table behind the fixed total bar?
If so, I would line up the Total title with the column text. 

<img width="989" alt="Screen Shot 2020-10-29 at 12 16 59 PM" src="https://user-images.githubusercontent.com/43549567/97601533-a7972000-19e0-11eb-99e0-40d06a4e45a6.png">

**Comment by stuckless** [comment]
@bjornalm You should look at this as 2 different features.
Feature 1: A means to enable a 'total' row to the table.  This feature should really focus on the just the visual aspect of allowing this to happen, and given the data, render the data values with the UI styling.
Feature 2: For something like the StatefulTable provide an implementation that can sum up information using an aggregation function.

We don't want this tied to knowing all the data up front.  ie, in Maximo we could implement this and show totals but the table itself will not have all the data loaded.  The aggegration would happen outside the UI layer and happening the Data Layer.

So for the Base Table, you might add a `totals: {title: 'Total', columns: [{amount: 1500}]}` to the view or data model.  The StatefulTable could extend this, and provide something like `aggregators: {amount: sumFunction}`
In the stateful table you can apply the aggegrator to the loaded data, but, other users can simply aggregate that information externally and make it available to the table.  The challenge with the StatefulTable is that you'll need a way to tell the StatefulTable to recalculate the values to update the totals sections. (ie, data changes in the table, you'd want to recall the totals row)

**Comment by bjornalm** [comment]
> @bjornalm You should look at this as 2 different features.
> Feature 1: A means to enable a 'total' row to the table. This feature should really focus on the just the visual aspect of allowing this to happen, and given the data, render the data values with the UI styling.
> Feature 2: For something like the StatefulTable provide an implementation that can sum up information using an aggregation function.
> 
> We don't want this tied to knowing all the data up front. ie, in Maximo we could implement this and show totals but the table itself will not have all the data loaded. The aggegration would happen outside the UI layer and happening the Data Layer.
> 
> So for the Base Table, you might add a `totals: {title: 'Total', columns: [{amount: 1500}]}` to the view or data model. The StatefulTable could extend this, and provide something like `aggregators: {amount: sumFunction}`
> In the stateful table you can apply the aggegrator to the loaded data, but, other users can simply aggregate that information externally and make it available to the table. The challenge with the StatefulTable is that you'll need a way to tell the StatefulTable to recalculate the values to update the totals sections. (ie, data changes in the table, you'd want to recall the totals row)

Thanks for clarifying this further. I do think we want to keep the API for the Table and StatefulTable in sync, but we can simply allow the aggregated value to be either a primitive (that Maximo gets from the DataLayer) or a function. If the aggregated value is undefined we can use a default sum function. Since this is a calculated value it doesn't have to be a state in the StatefulTable. The calculation can be memoized in the Table if the value is a function. It would then also be possible for an App using the normal Table to pass a value function if all the data is in the table. Example definition:

```
    aggregations: PropTypes.shape({
      label: PropTypes.string,
      columns: PropTypes.arrayOf(
        PropTypes.shape({
          /** id of the column that should have its values aggregated */
          id: PropTypes.string.isRequired,
          /** the primitive value or function that will receive an array of values and returns an aggregated value */
          value:  PropTypes.oneOfType([PropTypes.func, PropTypes.string]),
        })
      )
```
That for Maximo can be used as:
`aggregations: { label: "Total" columns: [{id: "amount", value: "1500"}] }`

Is there any reason you can think of for the primitive value to be a number? If the primitive value is a string you can format the value any way you want and we don't need a valueFormatter function.
