### ISSUE TITLE
[DashboardGrid / Card] allow resizing by dragging the border

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1598]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Currently, the only way to change the size is to do it programmatically. It could be beneficial to allow the user to drag the border of a card while in a DashboardGrid to resize it and see the changes or previews live.

This would probably only be worth effort if we can truly lock the resizing to each of our predefined sizes. If we have to actually try to adapt our styling to each completely custom size, it would be costly

**Additional context**
React grid layout allows resizing of items and allows min and max widths / heights so I believe this is possible.

Related props: https://github.com/STRML/react-grid-layout#grid-item-props

Related demo: https://strml.github.io/react-grid-layout/examples/0-showcase.html

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by bjornalm** [comment]
I found a UI design for the drag and drop (a bit by accident) and it looks and works a bit different from the resize functionality of the underlying react-grid-layout lib. 

https://pages.github.ibm.com/ai-applications/design/patterns/dashboard-config-v2/overview

Should we try to use this design?

**Comment by dianatran18** [comment]
Yup this was our UX proposal for drag and drop (along with the programmatic way to resize in the configuration panel), but if there are technical limitations we can discuss what options are available for this.

**Comment by bjornalm** [comment]
@dianatran18 Great! Where can I access the details of the specs (colors, borders etc)?

**Comment by bjornalm** [comment]
@scottdickerson @davidicus Our version of the react-grid-layout library (0.18.3) only supports resizing by a handle in the south-east corner
![image](https://user-images.githubusercontent.com/5167091/96100084-40537900-0ed4-11eb-9f43-55c6f77f73cb.png)

If we upgrade to the latest version (1.1.1) we can use the horizontal (west) & vertical (south) border resize as shown in the PAL design. I've tried it and it works, but since it requires a major upgrade of the react-grid-layout perhaps that should be done in a separate issue and we stick with the corner resize for this issue?

**Comment by davidicus** [comment]
@bjornalm that sounds like a good idea. We can deliver the initial feature and then upgrade in a separate issue.
