### ISSUE TITLE
[SideNav] implementation discrepancies

### ISSUE THREAD

**Issue by Ivan-Bachev** [carbon-design-system/carbon-addons-iot-react#1618]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

We noticed the following discrepancies in the SideNav component implementation. See the attached screenshots compared to what we designed and a list describing the issues.
 
![SideNav - issues](https://user-images.githubusercontent.com/70877374/93847446-99eace00-fcaf-11ea-8d2d-d94e383a900a.png)

1. There is an extra spacing above the first item in the implementation
2. The icon size is implemented as 16x16px but by design it should be 20x20px 
3. The text in the SideNav items shouldn’t be bold _(it should also be white, not sure why in the React implementation some items appear with grey text)_.
4. Indentation of child items with children doesn't match indent of child items with no additional children _(this is not clearly captured in the above screenshots comparison, but persists as an issue)_
5. The selected SideNav item should be shown with light background and left blue border _(this shows correctly on the React code but not in the TRIRIGA implementation)_
6. The height for child items should be 32px height instead of 48px

### Additional context

Storybook SideNav - component
https://carbon-addons-iot-react.com/?path=/story/watson-iot-sidenav--sidenav-component

AI Application Design SideNav - usage
https://pages.github.ibm.com/ai-applications/design/components/ui-shell-side-nav/usage

TRIRIGA SideNav - documentation
https://ibm.invisionapp.com/share/ZMNZSMJVSUY#/319510824_Navigation_Components_-_Side_Navigation

**Comment by tay1orjones** [comment]
Thanks for opening this Ivan, it's very helpful to see the current state vs what you expect. Some of these are defects from a recent upgrade of our Carbon dependencies and are contained in https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1584

> 1. There is an extra spacing above the first item in the implementation

This is present in the [Carbon spec](https://www.carbondesignsystem.com/components/UI-shell-left-panel/style#structure). To my knowledge we have not deviated from this. The design website lists the deviations [here](https://pages.github.ibm.com/ai-applications/design/components/ui-shell-side-nav/usage#how-we-deviate-from-carbon). @dianatran18 have there been updates to this guidance that aren't published on the website yet?

> 2. The icon size is implemented as 16x16px but by design it should be 20x20px

The [Carbon implementation](https://react.carbondesignsystem.com/?path=/story/ui-shell--side-nav-w-large-side-nav-items) uses 16px

> 3. The text in the SideNav items shouldn’t be bold _(it should also be white, not sure why in the React implementation some items appear with grey text)_.

To be fixed by https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1584

> 4. Indentation of child items with children doesn't match indent of child items with no additional children _(this is not clearly captured in the above screenshots comparison, but persists as an issue)_

To be fixed by https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1584

> 5. The selected SideNav item should be shown with light background and left blue border _(this shows correctly on the React code but not in the TRIRIGA implementation)_

I don't think there's anything we can do for this one as it looks correct in our storybook. My first thought it is that it might be an erroneous css override conflict present in the TRIRIGA implementation.

> 6. The height for child items should be 32px height instead of 48px

Only the SideNavMenu accepts the `large` prop to turn on/off the large/small sizing. This would change the size of both the high level item "Requests" as well as the children items "Manage Requests" etc. You can override the sizing via css to achieve your design.

**Comment by jm986** [comment]
@tay1orjones on item 5 I don't think we have any overrides. When I created the starter app I saw this styling missing in that package. I think it was on an older version though.
