### ISSUE TITLE
[Card] Add isSelected prop to Card (and ValueCard, BarChartCard, etc...)

### ISSUE THREAD

**Issue by bryancboyd** [carbon-design-system/carbon-addons-iot-react#1621]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

In the dashboard editor work, there is a need to render a card as "selected" for editing.

![image](https://user-images.githubusercontent.com/2175647/94032507-a2153d00-fd85-11ea-9e18-7ee0612d6f01.png)

If we want to render the border on the outside of the tile content (which might be preferable for usage in a dashboard), the following should work:

```
{
  border: solid $spacing-01 $interactive-04;
  box-sizing: content-box;
  margin: -$spacing-01;
}
```

**Comment by davidicus** [comment]
@bryancboyd @scottdickerson 

Question on the UX of this feature. With the isSelected Prop, does the component handle when this would be applied (ie. onClick, onKeypress)? Since there are so many interactive pieces that can be in both the header or body we cannot reliably tell when the user wants to click to select or is clicking an interactive element of the card. 

We could either:

- add a selection icon
- leave the application of this prop to the consumer who can update the boolean. We would have to drill an onClick handler down to the Card Wrapper to catch the entire cards click events. 
- make `isSelected` a function that has the logic to tell what is clicked and can return true if that  click should trigger the selection. Then the component updates the selected state internally. 
```
const handleSelection = (e) => {
    if (
      (e.type === 'click' && isSelected(e)) ||
      e.key === 'Enter'
    ) {
      setIsCardSelected(!isCardSelected);
    }
  };
```

What do we think is more flexible and can cover the use case in monitor?

**Comment by bjornalm** [comment]
I think alternative 2 (leave it to the app) would be very flexible. The context (where and when in the app the card is used) should probably determine if the card is being selected or being interacted with.

FYI. As part of #1598 I've added a blue border just like this that appears when the card is being resized. According to the video design here https://pages.github.ibm.com/ai-applications/design/patterns/dashboard-config-v2/overview#resizing-cards it doesn't look like the card is getting a border because it is "selected", it looks like the border appears only during drag resize and that is how I implemented it. This state is kept in the card and the app does not have to manage it.

But I don't think that there has to be a conflict between this resize-border and a selected-border feature.

**Comment by sstone2423** [comment]
This was discussed in Monitor's playback yesterday. Originally the idea was to have selected cards have a blue border, but that conflicts with Carbon's standard for focus outlines, which seemed confusing if a user tabbed into the card toolbar. 

In the current basic implementation, we removed the selected border altogether and just used the focus outline, which is also confusing because theres no obvious indication which card is selected.

After the playback, it was recommended that we could use a solid black border to indicate the selected card, which I'm planning to implement in the next iteration. I was unaware that we were working on resizing so I think we should plan a meeting together to discuss how selection and resizing would affect each other

**Comment by davidicus** [comment]
@CynZhang do you have any clarity on this [comment](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1621#issuecomment-713816017)
