### ISSUE TITLE
[Repo]Build test app that can spin up in CI to test build 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1730]
We need to have a way to test down stream consumers build using our package. We need to leverage our test CLI to build an app in our continuous integration tool.

- [ ] It should be able to create the project
- [ ] install our package as dependency
- [ ] run a build without errors
- [ ] Try selecting component on page?

**Comment by tay1orjones** [comment]
I attempted to do this with a CRA a few months ago. The primary challenge I ran into was that a CRA can successfully _build_ but still fail to _start_ due to runtime errors. If the CI script starts a CRA (or any similar app), it automatically goes into a watch mode which doesn't have a successful exit code. I was unable to find a way to determine if the CRA had started successfully.

> Try selecting component on page?

This is interesting, because if we were able to spin up an app and then assert things on the page, we could probably rely on it to fail if there are runtime errors. Even just finding/clicking a button would fail as the page would fail to load, or present an error message.

With this in mind:

#### 1. Update `create-iot-react-app`:
- add a base cypress set up to `create-iot-react-app` 
- add a handful of very simple tests to smoke test that things are building and running
- add a way to configure which bundle the app should use. 
  - `npx create-iot-react-app appname --bundle umd` would configure the imports to use 
`import Button from 'carbon-addons-iot-react/umd/carbon-addons-iot-react'` 
and the style import would be css instead of the scss.

#### 2. Extend `carbon-addons-iot-react` CI to run smoke tests:
- add new GH workflows/actions that create a `create-iot-react-app` and then runs the cypress tests as a smoke test
- actions can run concurrently, so we can create 1 workflow/action per bundle type 
    - `smoke test - umd/css` - run `npx create-iot-react-app appname --bundle umd`, run cypress tests, run a prod build
    - `smoke test - es/scss` - same as above, modified for es/scss
    - `smoke test - cjs/scss`- same as above, modified for cjs/scss

**Comment by JordanWSmith15** [comment]
Giving a value of 2 as it seems this would add stability/reliability
