### ISSUE TITLE
[CardEditor] TableCard editing support

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1739]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

`TableCard`s should be editable in the `DashboardEditor` via `CardEditor`. Similar in scope to the [TimeSeriesCard](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-cardeditor--for-timeseries)

**Additional context** 
- [Internal issue 1154](https://github.ibm.com/wiotp/monitoring-dashboard/issues/1154)
- Related: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1713

### Specific timeline issues / requests

Marked as a `val:1`, adding to the core team's scope for November.

**Comment by bjornalm** [comment]
I assume the [internal issue 1154](https://github.ibm.com/wiotp/monitoring-dashboard/issues/1154) describes a specific usage and that we have to translate it to a more general table card editing functionality for our library. Since we are in a hurry I would really appreciate some additional information on what we are expected to build and how it should act/look. Ideally an exhaustive UI design spec, but if not then having someone translating the internal spec to a clear spec for our library. Otherwise I’m afraid that I would be stuck with questions for many of the requirements listed.

The internal issue starts with a list before coming to the actual user requirements, where it states:
_"An administrator wants to be able set these Table Card data values visible on a instance or summary dashboard without using JSON"_  but exact what UI or functionality each item on the list require is not clear. 
- URL link Action
- Content Columns to include in a table .using Metrics, Calculated Metric, Dimensions, Constants, Links, Alert Data
- Column header Label Text
- Attributes - For icon status
- Row Value
- DataFilter
- Thresholds - using constants, metrics or dimensions
- DatatSource
- Attributes
- Range
- GroupBy

I can understand how we can create a UI for toggling visible columns and modifying column names etc if the App provides us with an initial list, but other items like the “Row Value” is more confusing. In the widest definition I can interpret that as an external visual data editor (like the table inline row editor but outside the table). The TableCard has a `values` prop which essentially is the data for all the rows, and another item on the list is the "DatatSource"  which leaves me guessing what is expected here.

**Comment by tay1orjones** [comment]
Yeah, it's not super clear from the spec what exactly this entails. As we discussed, we'll defer this one until we have a more defined scope from design.
