### ISSUE TITLE
[Table] Button icon in custom toolbar has incorrect position

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#1915]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

If the table has custom toolbar, and there is a button with icon in the custom toolbar,  then the icon position is not correct on Safari.  All buttons with icons produce this invalid result . 

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/65387028/103725309-4196cc80-5011-11eb-9c6c-028df49a13b8.png">

### Environment/versions:
- `Browser`: [`Safari` Only]
- `carbon-addons-iot-react` version: [e.g. `v2.141.0`]

**Comment by davidicus** [comment]
Hi @zhaozhuo813. Do you happen to have the `carbon-components-react' and/or `carbon-components` package installed. If so there may be some styles being overwritten. I ask because I do not see this issue in our storybook when I add a custom button with icon to our table toolbar. If you are using `carbon-addons-iot-react` package we ship the appropriate version of the carbon packages so it is unnecessary for your app to do so as well. 

![image](https://user-images.githubusercontent.com/1590966/104046716-80ae5480-51ae-11eb-8a10-e35429533fa7.png)

**Comment by davidicus** [comment]
closing this since I believe removing extraneous packages should provide the fix. Feel free to reopen if the issue persist.
