### ISSUE TITLE
[Table] `size` prop does not make header any smaller

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon-addons-iot-react#1986]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

There a Carbon/PAL table `size` prop. I can be used to make the rows and header larger, but doesn't work with "compact" and "short" sizes. Those will shrink the rows, but not the header.

Additionally, if rows have row actions, those buttons enlarge the rows, so they can't shrink either.

This works with the Carbon DataTable directly.

This is not a critical problem, but does make it harder to integrate this table into some "legacy app" pages where other tables/lists are much more compact.

### To Reproduce

Use prop `size: 'small'` or `'compact'`.

Normal size:
![image](https://user-images.githubusercontent.com/805573/106212779-2aff1380-6180-11eb-879c-d819526d44e1.png)

Small size (notice header doesn't shrink):
![image](https://user-images.githubusercontent.com/805573/106212799-36523f00-6180-11eb-9985-10633ebe3613.png)

### Expected behavior

Rows *and* headers shrink in size. Including rows with row actions.

### Environment/versions:

- `carbon-addons-iot-react` version: [e.g. `v2.98`]

**Comment by gillibrand** [comment]
We're now getting pressure to use the "compact" size to integrate with our existing UI design (or maybe just for data density--not clear). So the ELM project would really like to see this addressed. I haven't investigated yes if this is something we can work around with custom CSS.

**Comment by davidicus** [comment]
Hi @gillibrand . We never had the push to update our table to support the size prop seen in Carbon because of the issues you mentioned. Table cells will always grow to allow room for their content regardless of the height prop. Since this is not obvious to some devs we left it up to the discretion of the consuming developers to change with CSS. We even have a story were we highlight [this](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-custom-row-height).  If you open up the inspector and change the height to `1rem` you will see the table rows never shrink below `37px` and this is without any action buttons. 

This decision was made a long time ago before we had cell truncation so perhaps this can be revisited. Although, tables that have action buttons or custom content that can not be truncated will still have the same issue.  @dianatran18 Does design have any new thoughts on this matter?

In the meantime, If the content of your table allows for the compact rows it is def something that can be resolved with CSS.

**Comment by gillibrand** [comment]
For the the rows, I understand that the the content will increase their height, that's fine. But I would expect that the headers (which only support text in them that I know of) would respect the size. Either way, if it won't be supported by PAL I can take care of it with CSS on my end for now.

What I'm not clear on is if this issue should just be closed as "not-supported/working as designed", or whether there is an issue here for PAL. If it's not supported then the "size" prop probably shouldn't be passed through to the Carbon DataTable at all. If it is supported, then the headers should resize. So I'll leave it to you to decide if this should be closed or not. Custom CSS seems to be the resolution for me personally though.

**Comment by JordanWSmith15** [comment]
Upping the priority on this. Spoke with Diana, and the direction is to follow Carbon's design guidance, though we will need to weigh effort and risk https://react.carbondesignsystem.com/?path=/story/components-datatable--playground

**Comment by dianatran18** [comment]
Carbon has always supported multiple table sizes, but from what I know it was a conscious decision to use the 48px table size for the IoT data tables so that there are large enough touch targets for all of the rows and actions. @davidicus @lukefirth correct me if I'm wrong there.

I've definitely seen teams use the smaller table sizes for data density reasons within Sterling (Angular), so from a design perspective we should be able to support the smaller sizes for that reason, but to @JordanWSmith15's point we need to weigh effort and risk for everything that has been built on top of the PAL react data table.
