### ISSUE TITLE
[rollup] Half of carbon-addons-iot-react bundle size is coming from core-js and moment

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2006]
### What package is this for?

- [x] React
- [ ] Angular

This is a request to add peer dependencies for moment and corejs or do something to reduce the bundle size as half is being consumed with moment and corejs

![image](https://user-images.githubusercontent.com/6663002/107055310-64daa600-678e-11eb-85b3-90825fefcedb.png)

I see code in the webpack.config to remove the moment locales from the bundle, but nothing on the rollup size to really stop us from packaging it.

**Comment by sstone2423** [comment]
It might be expensive, but moment has recommended projects to no longer use it in favor of the native Intl javascript object

**Comment by stuckless** [comment]
I guess the question becomes... if you make it a peer but the carbon / PAL components require it... does it save anything in the end, if you have have to manually add this to each project in order for the project to compile/work?

**Comment by kevinsperrine** [comment]
@scottdickerson Can you re-run an analysis on the latest version of `next` now in your application? Since this issue was opened we've replaced moment with dayjs and fixed tree-shaking in the build process, so you should have a significantly different output now. We're still bundling all locales so dayjs accounts for 10.2% of the build (9.6% or 206.92KB in locales), but corejs only accounts for 3% (or 64.6KB). 

![Screen Shot 2021-09-13 at 1 34 59 PM](https://user-images.githubusercontent.com/609466/133130882-ac833697-ba90-4139-a6c5-27ea566f5c89.png)

**Comment by davidicus** [comment]
closing this issue as things have changed pretty drastically and we have seen some improvements in package size. Additional work may need to be done regarding dayjs but this will be tracked in  another issue.
