### ISSUE TITLE
[Table] Allow HTML or component column titles

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon-addons-iot-react#2077]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

I have at least three uncovered use case for title columns:

1) Use an icon only for the visible column "name". This is for columns that themselves just show status icons, so a full name is wasteful of space. See the "has comments" column below.
2) Columns with icon decorators. See below for an "Embedded In" link column that show an orange left-arrow in indicate it's an incoming use case.
3) Long tooltips on columns where embedded help is required.

I think all of these can just be solved by the app if columns can provide either their own HTML or a custom React component for their titles. Only text labels are supported currently.

![image](https://user-images.githubusercontent.com/805573/109544360-4fe6ef00-7a7c-11eb-91dc-a3b056626f06.png)

### Specific timeline issues / requests

Elm 7.0.3. Around June.

**Comment by davidicus** [comment]
@dianatran18 Do we have any design guidance around this?

**Comment by dianatran18** [comment]
1. For icon-only columns, this is the guidance we have around that right now: 
https://pages.github.ibm.com/ai-applications/design/components/datatable/columnalignment#icon-only-columns
I think having text in the icon-only column header makes it more clear than just having an icon, as icons can be ambiguous and may not always be clear to users. Especially since the rows in the column are all icons, having a descriptive column header is valuable. 

2. Similar to the first answer, I think relying on the icon alone to describe "incoming" in this use case is a little ambiguous and not very clear. Having icons in the column header also starts to add more clutter to an already dense data table, and starts to compete with other icons associated with the column header such as the sort icon. I think using the tooltip to help further describe the column is valuable and works better than the icon. In this specific use case, the color of the icon also conflicts with hover/sort states for the column header, and wouldn't pass accessibility against any column header background color. 

3. This we did just add recent guidance on, which you can find here: 
https://pages.github.ibm.com/ai-applications/design/components/datatable/general#column-header
This was feedback we received from MAS to try to create more alignment on how we display tooltips in column headers. Similar to everything described above, we're trying to move away from using info icons in the column header, as it adds more clutter and also competes with other icons such as the sort icon. We are recommending to use the [definition tooltip](https://www.carbondesignsystem.com/components/tooltip/usage/#definition-tooltip) styling Carbon provides to display tooltips. 

@davidicus I believe there's a related issue or conversation somewhere about using the definition tooltip in column headers right?

**Comment by kevinsperrine** [comment]
> @davidicus I believe there's a related issue or conversation somewhere about using the definition tooltip in column headers right?

@dianatran18 #2272 was merged last week for tooltips in the headers. See [this story](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-column-tooltip).

**Comment by davidicus** [comment]
Based on the feedback above I am going to close this issue as it sounds like this is not a desirable pattern for the PAL or AI applications. If there are constraints that won't allow you to change this pattern in your app let's discuss in our PAL office hours so we can work on possible solutions and/ or any safety hatches we may need to code in to allow for variances.
