### ISSUE TITLE
[SuiteHeader] Masthead dynamic company name

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2117]
### What package is this for?

- [X] React

### Summary

Currently, the text "IBM" cannot be edited in the MAS header. Large business partners who preform heavy configuration have the right to re-sell applications or entire Maximo instances branded as their own. 

### Specific timeline issues / requests

MAS 8.5
We need to add a configuration property to allow for this. 
![brand-name](https://user-images.githubusercontent.com/21066152/110968382-71ba5e80-8325-11eb-863d-10dafcb13fc3.png)

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by kevinsperrine** [comment]
@JordanWSmith15 The `SuiteHeader` allows passing all the same props as `Header`, so IBM can be changed in `SuiteHeader` using the `<SuiteHeader prefix="KSP" />` prop. It does not show up in documentation because the Header propTypes are not being extended in `SuiteHeader` we can fix that with this issue to make it more clear.

<img width="755" alt="Screen Shot 2021-07-13 at 5 05 27 PM" src="https://user-images.githubusercontent.com/609466/125524915-e1e66d54-e813-4797-b8b7-668d0e4bcc89.png">
