### ISSUE TITLE
[Component Proposal] Map Component

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2157]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
A continuation of the exploration [issue](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1347), this issue is to track the development of the various pieces that are used to interact with the map. Since different map providers have their own unique APIs this component will provide the target element as well as props to power the various controls, labels, and headers but consumers will have to instantiate their own maps and pass the appropriate props. 

We will have working storybook examples using MapBox and OpenLayers map providers. 

**Additional context** 

Design specs for the map component have been published on our design site [here](https://pages.github.ibm.com/ai-applications/design/patterns/maps/overview/).

**Comment by bjornalm** [comment]
Left to do for this PR is:

- map config button should only be available in full page view
- full page map should have show the minimize/close button to the right, after the settings button
- full page map should have the settings icon aligned with the map controls below
- full page map controls should be size 40px instead of 32
- full page map should have 32px space between border and map controls instead of 16px 
- map watermarks  are not positioned correctly
- create new scrolling map controls container
- flyout controls should have little arrow to indicate flyout                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
- map controls should be shown/hidden depending on available height space in card
- create example with related content as map overlay (panel inside card)	
- legend container should have 80% opacity and dropshadow
- full bleed legend should should be collapsable

- scrollbars and white space outside map appear when going to full page view. Probably related to the map settings panel
- in open layers example the fullscreen button opens up map configuration
- clicking close x on map configuration doesn't close the map
- there should be an example of map controls acting like toggle controls, current controls behaves like radio buttons.

- add actions for the stories
- add unit tests 
- i18n
- documentation
- export component in index.js

- drag and drop of related content panels inside card (stretch goal)
- Have it work in the actual old deprecated dashboard (stretch goal)
