### ISSUE TITLE
[BarChartCard] xaxis is ignoring the locale property

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2305]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
Pass locale french to the Dashboard Editor, notice the x-axis formatting of the line chart uses the correct french months, but the bar chart doesn't

![image](https://user-images.githubusercontent.com/6663002/117474465-292fb380-af18-11eb-8560-5cf59c0bf9de.png)

**Comment by jkeen** [comment]
Looks like `carbon-charts` uses `date-fns` and to format date labels they're expecting you to pass in a `date-fns` locale object, like this: 
```js
 import frLocaleObject from 'date-fns/locale/fr/index';

 ...
 export const chartOptions = {
  axes: {
    left: {
      mapsTo: 'value',
    },
    bottom: {
      mapsTo: 'date',
      scaleType: 'time',
    },
  },
  timeScale: { 
    localeObject: frLocaleObject 
  }
 };
```
I wish they'd take a string and load the object automatically, but a similar issue has been brought up [already](https://github.com/carbon-design-system/carbon-charts/issues/558#issuecomment-610755570) and supporting auto switching would require them including all the locales in the charting lib

Didn't realize we already had `date-fns` included in our bundle otherwise I would've worked harder to get it working instead of dropping in `dayjs` (which we are currently including all the locales from) in #2187

**Comment by JordanWSmith15** [comment]
This seems important for any team using charts in MAS
