### ISSUE TITLE
[GuageCard] content is cut off at smaller sizes

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2407]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The extra content like the trend indicator of the gauge card is cut off at smaller sizes

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-gaugecard--basic-with-expand
2. See error

![image](https://user-images.githubusercontent.com/1590966/122059071-42027300-cdba-11eb-86c5-04825f452193.png)

**Comment by davidicus** [comment]
@scottdickerson have you all seen this in monitor and have you worked around this?
@dianatran18 FYI If we are still discussing card sizes.

**Comment by dianatran18** [comment]
This is why we moved away from smaller card sizes like this (we recommend a 4 column card being the smallest) but I know some teams had pushed to keep the small size since it's already used in product. So if these are being used, the limited space for content should be accounted for by the product team.
