### ISSUE TITLE
[ImageHotspots] hotspot positions are incorrect

### ISSUE THREAD

**Issue by JoelArmendariz** [carbon-design-system/carbon-addons-iot-react#2417]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
If you add a hotspot to an Image card on the bottom edge via the dashboard editor and save it, the card shows the hotspots inaccurately. I think this is true for image cards with hotspots in general.

### To Reproduce

Go to the dashboard editor => add an image card => edit the image and add a hotspot to each edge => save it and see that the hotspots have moved up.

### Expected behavior
Hotspots should stay accurate.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

![image](https://user-images.githubusercontent.com/53092833/122232676-09799c80-ce81-11eb-83ea-9f220f9161f7.png)

![image](https://user-images.githubusercontent.com/53092833/122232702-0e3e5080-ce81-11eb-894e-83499dc7f01b.png)

 - Here is the image I used to recreate this: 
 - 
![test_image](https://user-images.githubusercontent.com/53092833/122232803-201ff380-ce81-11eb-8cbb-cf24acd02cea.png)

**Comment by bjornalm** [comment]
I had a look. I think it has to do with this section of the code
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/src/components/ImageCard/ImageHotspots.jsx#L677-L691

The image container is adjusted depending on scale and the `displayOption`, but the hotspots container is not. I don't even think the code for the image container is correct. But for sure we are missing how to set the correct height and width of the hotspots container (using `hotspotsStyle`) depending on the image orientation in combination with the `displayOption` which can be `fill`, `contain` & `cover`. So I think we have to:

1. Make sure we always get the `displayOption` value (it is sometimes null when used in the HotspotEditorModal)
2. Find out the actual size if the visual image since it might not be the same as the size if the image element when the displayOption is being used
3. Make sure all different combinations are supported

**Comment by scottdickerson** [comment]
we can remove cover it's fine with me @bjornalm thanks
