### ISSUE TITLE
[DataTable] Adding columns ignores the defined widths

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2460]
### What package is this for?

- [ ] React

### Summary

In storybook https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-resize-on-column-resize-callback-no-initial-column-width-and-column-management
1. Alter the field "The width of the added columns (if any)" to be 500px
2. Click "Add" 
Result:
Column added is still 150px wide
Expected:
Column added matches the desired width, causing a horizontal scroll if necessary

This seems to be effecting our ability to insert columns at a wider size in Health

**Comment by bjornalm** [comment]
In the story this issue is referring to it was never possible to add a column and get a horizontal scrollbar as a result. It was possible to add a column with specified width but the total width of the table would not change, instead the other columns would shrink. 

With this PR https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2131 which solved issue https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2061 the width of a new column is ignored for a table with resizable columns, so the story itself makes less sense now. 

However, later we introduced this PR https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2306 that makes the last column resizable to the right and hence fixes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2061 in a different way so it would be possible to undo PR https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2306

We have been going back and forth on how to handle column resize and column insertion in lack of a clear specification. Is it a requirement for you to add a column with a specified width when the columns are resizable? If so, what are the table configuration you are using for that?

**Comment by davidicus** [comment]
@dianatran18 I would like to set up some time to discuss next week to iron out some of the details for this.

**Comment by bjornalm** [comment]
See issue #2471

**Comment by jimcrosskey** [comment]
@bjornalm @davidicus @JordanWSmith15 In my mind there should be a default column width for each column (title width?).  When columns are added it does not shrink existing columns or add new columns with width less than that default width.  If not all columns can be displayed in the viewing area, it should present a horizontal scroll bar.  The user can of course manually resize any columns to be less than the default width and that width would be preserved when adding a new column.  Hope this helps, happy to be part of the discussion.  here is the issue in the Health repo https://github.ibm.com/maximo/Asset-Health-Insight/issues/5423

**Comment by JordanWSmith15** [comment]
> In my mind there should be a default column width for each column (title width?). When columns are added it does not shrink existing columns or add new columns with width less than that default width. If not all columns can be displayed in the viewing area, it should present a horizontal scroll bar. The user can of course manually resize any columns to be less than the default width and that width would be preserved when adding a new column. 

@jimcrosskey Exactly. This is the same approach I stated last week in our meeting, @davidicus @dianatran18

**Comment by bjornalm** [comment]
This issue has been discussed in a couple of meetings now and we are going to modify the current behaviour so that the table width increases when new columns are added if there is not enough space, which as a consequence normally would mean that a horizontal scrollbar appears. If the table is wider than the parent element, i.e. it has horizontal scrollbars, and a column is removed, the width of the table will shrink. This new behaviour might be configurable with a new prop to make it optional. We probably still need to hammer out the exact details because there are a lot of parameters and different configurations at play here (issue #2471).
