### ISSUE TITLE
Column customization - Design specs

### ISSUE THREAD

**Issue by Najil-K** [carbon-design-system/carbon-addons-iot-react#2603]
### What package is this for?

- [x] React
- [ ] Angular

PDF Format: [Column customization#694@2x.pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6822929/Column.customization.694%402x.pdf)

![Column customization#694](https://user-images.githubusercontent.com/81316430/125785629-d82eb97c-bd3b-4c8d-9230-212ed0d1d57f.jpg)

### Available extra resources
PAL component guidance reference:
https://pages.github.ibm.com/ai-applications/design/components/datatable/columncustomization

Box-folder with assets:
https://ibm.box.com/s/1mjregg7iwvmmue1b5sqsy7hrtglhpio

Box spec note: https://ibm.box.com/s/evpypmmv4fcmq0c8vfawlumgogizlvac

**Comment by dianatran18** [comment]
Yes, column group selection/reordering support will work with this much easier than the older reordering pattern that's inside the column header. We didn't create a spec for that since teams haven't asked for it, but generally any list/list builder variations can work in this use case.

The one part that could still get confusing is reordering child group columns outside of the parent columns, but if we only allowed reordering at parent levels and single column levels you'd be fine there.

**Comment by bjornalm** [comment]
@davidicus 
1. Should this replace the existing built in column reorder functionality or be an alternative to it? 

2. Should we build this as an internal component (like the MultiSortModal) and let the table handle everything or do we try and keep it separated and build it as an external component (like the SaveViewModal). The amount of wiring needed to get it working as an external component will be fairly limited, i.e. add a button to the toolbar that opens the ModalComponent we provide and update the table with the the modified ordering prop when the modal is saved.

As a principle it could be wise (for us) to add new table functionality outside the table if possible in order to reduce the complexity and size of the table component. If the answer to question 1 is to replace then building it as an external component will be a breaking change though.

**Comment by dianatran18** [comment]
Can this be considered a V2 or new version instead of replacing the existing? I don't want this to break team's tables and current implementation if designers haven't accounted for it in the design yet/they're not prepared. But I don't know what the best transition is for that, so @davidicus can decide.
