### ISSUE TITLE
[Table] Group Column Headers

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2794]
### What package is this for?

- [X] React
- [ ] Angular

### Summary

Support table header grouping labels
Design spec:
https://pages.github.ibm.com/ai-applications/design/components/datatable/groupedcolumns
![Screen Shot 2021-09-02 at 10.15.56 AM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/bec27e8f-7fec-43c5-9f78-02773f2e5d74)
Need to ensure that text ellipsis occurs on strings that do not fit, and provide either a Carbon or browser tooltip to display the full label
We will need to disable column resize and column pickers when grouping is enabled

**Comment by JordanWSmith15** [comment]
Relates to https://jsw.ibm.com/browse/GRAPHITE-40207

**Comment by JordanWSmith15** [comment]
Examples of use:
https://ibm.invisionapp.com/share/C9O1DLYABNS#/screens/320092867
https://ibm.invisionapp.com/d/main#/console/15378790/320044391/preview

**Comment by bjornalm** [comment]
@JordanWSmith15 I can't access 
https://ibm.invisionapp.com/d/main#/console/15378790/320044391/preview
and
https://jsw.ibm.com/browse/GRAPHITE-40207

**Comment by dianatran18** [comment]
I've seen grouped column headers be used in data tables, but I don't know if I've seen it within column customization capabilities (the table might be defined for the user as-is).

We might need to lean on the teams using the grouped column headers to understand what use cases they have, and what columns would need to be reordered if that's needed. I can't imagine use cases of moving child columns outside of their parent columns for example, because the parent column provides the context of the child column, but that's an assumption. 

At most, I can imagine reordering full groups (parent column with all children below it) or maybe reordering the child columns inside of the parent, but not mixing and matching columns.

**Comment by JordanWSmith15** [comment]
@bjornalm updated link to https://ibm.invisionapp.com/share/C9O1DLYABNS, and added you to graphite project
