### ISSUE TITLE
[StatefulTable] reset current page to page 1 when changing page size

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2924]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

OLD DESCRIPTION, SEE COMMENTS BELOW:

Currently, the StatefulTable will reset back to page 1 if you change the page size parameter. We've adjusted the HierarchyList to maintain the same page and show the items that should be on that page given the new size parameter (https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2920). For consistency, we should do the same with the StatefulTable.

### To Reproduce

1. open the [StatefulTable story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--simple-stateful-example
2. turn on pagination
3. set page size to 30
4. move to page 3
5. change page size to 10

Table should stay on page 3 and adjust to show only ten items.

**Comment by bjornalm** [comment]
Where is this requirement coming from? I'm asking since I don't understand the use case for staying on the current page when changing page size. 

For example, page size is 10 and the user is on page 5 (i.e. viewing rows 41-50) when he/she changes page size to 30. I would assume the reason for doing so would be because he/she is not finding a specific row and wants to move faster while "browsing" for it. If the table then starts showing rows 141-150 on page 5 then the user can't continue "browsing" for the item by going forward since there is now a gap of a hundred items that haven't been viewed. In this case I think it would make more sense to show the page containing row 50 (the "largest" item last shown) which would be page 2 in this example. BUT, I might be missing some use case here, hence my question.

**Comment by bjornalm** [comment]
After talking with @kevinsperrine (who had discussed this with @dianatran18) we should keep the original behaviour which is resetting the page whenever the page size is changed. I'm gonna add a unit test to confirm the functionality.
