### ISSUE TITLE
[ComposedModal] prevent height of modal to change with content

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#3077]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

The height of the modal currently changes with the content, e.g. the height of the modal is decreased if the user reduces the number of items in a list using search. We can set a fixed height of the modal content but doesn't take into account the actual viewport height and if we set the height of the content in `vh` we are still missing information about the space occupied by the surrounding modal (like height of header and footer that could vary).

Not sure what the best solution to this problem is. It could be nice if the content of the modal would be passed the maximum height allowed, which would be the viewport minus all modal paddings, margins, header and footer.

**Additional context** 
![image](https://user-images.githubusercontent.com/5167091/142624060-b94ce607-73c1-4c63-a103-384b157d2e07.png)
![image](https://user-images.githubusercontent.com/5167091/142624157-8ba695d5-606e-4572-9f81-6b13efc9f224.png)

**Comment by bjornalm** [comment]
@dianatran18 Any thoughts on this?

**Comment by dianatran18** [comment]
The main difference between this list builder, and the one we worked towards in the [data table column customization](https://pages.github.ibm.com/ai-applications/design/components/datatable/column-customization/usage) one is that Available list on the left doesn't shrink as you remove items from it. So in a search use case, the modal would also stay the same height as well and display an empty state. 

My other thought is that we can use the [tearsheet](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tearsheet--default) since the bottom of the container is pinned to the bottom. If you look at the guidance from [C&CS](https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/usage) (where it originally came from) there are technically two tearsheet sizes — wide and narrow. Although, narrow might be too narrow here..

**Comment by dianatran18** [comment]
@bjornalm how is the dynamic max height calculated? Is it like __px or __% from the top and bottom of the page?

Even looking at the example [here] I think it would be better to have a fixed height based on the page size, instead of the modal jumping in size when you add/remove items, or search. Is that possible?

**Comment by bjornalm** [comment]
Just to clarify,

1. The purpose of this issue is exactly what you are asking for, preventing the modal from jumping in size. 

2. This issue is for the ComposedModal in general. We use the ComposedModal as the main building block for several other components. I used the SelectUserModal in the screenshot to exemplify the unwanted search height jump behaviour that all components relying on the ComposedModal would experience unless they explicitly set a "fixed" height of the modal content (which is what I've done for #2603).

3. Today, there is no dynamic max height calculated. My suggestion was to calculate such value and pass it to the content so that all our modal components and client specific modals could us it to set the height of the content. I just wanted to verify that you agree that the "height jumping" was a problem.

Regarding the Tearsheet, yes that would have been a better option for these scenarios when dealing with large lists since it doesn't change in height depending on content. Why was it not used for the data table column customization design?

**Comment by dianatran18** [comment]
> Regarding the Tearsheet, yes that would have been a better option for these scenarios when dealing with large lists since it doesn't change in height depending on content. Why was it not used for the data table column customization design?

The tearsheet wasn't a component we had in the PAL at the time when we worked on the column customization modal back in January. 

Although the fixed tearsheet sizes and general capabilities (stacking tearsheets) aren't needed for this use case, so sticking with the modal is fine. 

I see in the Carbon style they specify max heights for modals: https://www.carbondesignsystem.com/components/modal/style#max-sizes

Here are two options:
- We can build this in a way that the modal height is based on how many items are in the available row (fixed at that height), and once it hits the max size of the modal, then you get a scroll through the list and it stays the max fixed height.

- We can always use the max height, regardless if the list of columns is long or short. 

My only concern with option 2 is if you had a table with only 5 columns, and you were on a large desktop then the modal would look a little empty. But would love to hear your thoughts on implementation. 


Also, there shouldn't really ever be a use case where the selected column is longer than the available column (there's some duplicates in this example so that's why it happened) but as long as we base the height on the available column there shouldn't be much jumping. 

<img width="755" alt="Screen Shot 2021-11-22 at 12 13 48 PM" src="https://user-images.githubusercontent.com/43549567/142905360-6e5f61ea-5c70-4a97-9f58-9fd5588b2e94.png">


And if the search results or selected column is empty we can use a fixed white container in the background based on the fixed height on the available side. 

<img width="577" alt="Screen Shot 2021-11-22 at 12 15 09 PM" src="https://user-images.githubusercontent.com/43549567/142905568-eb1b7659-495a-4936-8251-689386f6743e.png">

**Comment by JordanWSmith15** [comment]
@bjornalm  My preference to keep this contained and low-effort, using a consistent fixed height that makes sense (not too big, in case the user has a small browser height set).

**Comment by bjornalm** [comment]
Adding this as a problem that we should fix in this issue as well. It happens on small screens with the workarounds I created for the modal height in the TableColumnCustomizationModal.
![image](https://user-images.githubusercontent.com/5167091/144589310-654a02cb-91ff-451f-86c5-c9774dd2b52a.png)

Like the other issues I described it could also be solved by providing the content of the modal with the maximum height allowed.

**Comment by bjornalm** [comment]
Waiting for https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3114 to be merged since we need to measure the height

**Comment by stuckless** [comment]
I'm just going to throw some other stuff into the mix.

@dianatran18 The challenge with sizing the dialog based on "known" content is that in most cases that information is not known until AFTER the dialog is rendered.  ie, I don't know that I have 100 columns until I send a request to the server and ask "how many columns do I have".  This is the challenge with modals is that they are largely dealing with async data, so it is hard to size beforehand.  This is why I asked that the request for columns, etc, be async, and in fact, we should assume that ALL data is async when building pages, dialogs, etc.  So I was thinking about the typical use case for this select columns dialog... First time in... the "Available columns" (or entire dialog) is in a loading state, the selected columns is disabled until our columns are loaded.  We might load 2 columns or we might load 100, we don't know.  The second time in, we likely know how many columns we have (although it would still be async in terms of the UI, just the information comes back very quickly)

Personally, I would allow responsive sizes to dialogs that are sized as a % of the viewport and the, and then adjust those % based on breakpoints. Allowing an app developer to say "this dialog 800px high" is just going to lead to bad UI experiences across devices.  Carbon's guidance on this is actually very good, which surprised me, because typically they tend to not deal with responsive designs, but, in this case their guidance on dialog sizing is pretty good and I'd prefer to see that implemented vs a fixed pixel sizing.

I think that by allowing a size of xs, sm, lg, xlg, etc we can determine reasonable defaults for dialogs like this.  ie, it's probably reasonable to expect that tables will likely have 10+ columns (why else would I need such a complex dialog).  So we can use a default of lg or xlg and potentially allow for app dev to supply an alternate size on this dialog for the edge cases of "I want to have this dialog for only 2 columns in my table"

**Comment by bjornalm** [comment]
> I'm just going to throw some other stuff into the mix.
> 
> @dianatran18 The challenge with sizing the dialog based on "known" content is that in most cases that information is not known until AFTER the dialog is rendered. ie, I don't know that I have 100 columns until I send a request to the server and ask "how many columns do I have". This is the challenge with modals is that they are largely dealing with async data, so it is hard to size beforehand. This is why I asked that the request for columns, etc, be async, and in fact, we should assume that ALL data is async when building pages, dialogs, etc. So I was thinking about the typical use case for this select columns dialog... First time in... the "Available columns" (or entire dialog) is in a loading state, the selected columns is disabled until our columns are loaded. We might load 2 columns or we might load 100, we don't know. The second time in, we likely know how many columns we have (although it would still be async in terms of the UI, just the information comes back very quickly)
> 
> Personally, I would allow responsive sizes to dialogs that are sized as a % of the viewport and the, and then adjust those % based on breakpoints. Allowing an app developer to say "this dialog 800px high" is just going to lead to bad UI experiences across devices. Carbon's guidance on this is actually very good, which surprised me, because typically they tend to not deal with responsive designs, but, in this case their guidance on dialog sizing is pretty good and I'd prefer to see that implemented vs a fixed pixel sizing.
> 
> I think that by allowing a size of xs, sm, lg, xlg, etc we can determine reasonable defaults for dialogs like this. ie, it's probably reasonable to expect that tables will likely have 10+ columns (why else would I need such a complex dialog). So we can use a default of lg or xlg and potentially allow for app dev to supply an alternate size on this dialog for the edge cases of "I want to have this dialog for only 2 columns in my table"

I agree that the ideal scenario would be to rely only on predefined sizes as % of the viewport and breakpoints, and PAL can define default breakpoints and sizes but they are not guaranteed to work in all scenarios. This is because the height of the modal header is, like the content itself, also not known in advance. The application could for instance add a longer description in the header which on smaller screens would wrap multiple lines and consume a lot of height which could cause the PAL predefined height to be too tall. If that is an acceptable edge case that the application developer should deal with then that is fine, but we can also calculate an actual max-height that we add to the modal body in order for it to shrink when the header is taller than expected.

**Comment by davidicus** [comment]
My two cents here: I think Modals should have a min and max height set but dictating the actual height for anything seems like a way to have your content break out of its container in some scenarios. I am always loath to apply an actual height because of the dynamic state of a web page and the myriad of display sizes it can be viewed on.
