### ISSUE TITLE
[Table] Nested table test wrap

### ISSUE THREAD

**Issue by cgirani** [carbon-design-system/carbon-addons-iot-react#3129]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

For table nested table, at some point column can get overridden by one with bigger content
### To Reproduce

1. Go to StatefulTable with row nesting and resizable columns with initial width
2. Click on expand to one with 4 levels
3. See the error

### Expected behavior

Max-width of the span should be based on parent width - current offset

### Environment/versions:

- OS:  MacOS
- Browser: chrome
- `carbon-addons-iot-react` version:  `v2.147.0-next.79`

### Additional context

![image](https://user-images.githubusercontent.com/22034430/145400014-55b7e9c4-cd8d-4bf8-bc5d-362631dcdc5c.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Yes.
Is it related to an upcoming release? MAS Monitor.

**Comment by bjornalm** [comment]
Like @cgirani suggests we can reduce the width of the inner span with the width of the indentation to fix the overflow problem here.

But @dianatran18  Just want to verify, is this the way indentation was meant to work in the table? That **only** the first real data column gives up the space needed for the indentation. This will reduce the available space needed to render that column's data and a couple of levels down there won't be much space left. Another option is to propagate the indentation through all columns and let an additional last column deal with the different indentation spaces...

**Comment by dianatran18** [comment]
> Like @cgirani suggests we can reduce the width of the inner span with the width of the indentation to fix the overflow problem here.
> 
> But @dianatran18 Just want to verify, is this the way indentation was meant to work in the table? That **only** the first real data column gives up the space needed for the indentation. This will reduce the available space needed to render that column's data and a couple of levels down there won't be much space left. Another option is to propagate the indentation through all columns and let an additional last column deal with the different indentation spaces...

Yes, if you are using nested hierarchy in the table, and all of your other columns are the same, then it should only be the first column that is being indented. This allows for users to still compare the data against the other columns, but show the hierarchy.

In [our guidance], you'll see the do's and don'ts example here:

<img width="781" alt="Screen Shot 2021-12-14 at 9 43 04 AM" src="https://user-images.githubusercontent.com/43549567/146019969-32dd95f6-7e67-4a42-aee0-7ee99bdf907e.png">
 
If you know you are using the nested hierarchy table, I'd make sure that your first column has sufficient space to grow at the most expanded state. There shoudl also be a minimum padding at the end of each column, so that the content doesn't push into the next column's text. Generally, there is 16px on the left/right of each column's text.

**Comment by bjornalm** [comment]
Thanks, yes the fix submitted will make use of the existing padding
