### ISSUE TITLE
[Datatable] Table row data is needlessly constrained by Up/Down Sort Icon

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3473]
From https://jsw.ibm.com/browse/GRAPHITE-50211
when there's a table with sortable columns, the displayable area of the column EXCLUDES the vertical space taken up by the Up/Down sort icon.

See attached image... the red arrow points to the icon, and the braces show the area that should be available for displaying column data:

The App Name column has plenty of space to show the value of TECHMOBILE, but it shows "TECHMO...".  If you hover over the column header you will see the Up/Down sort icon appear and see that it is constraining the displayable width of the column text.
![image-2022-06-15-18-29-18-762.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/bb74bb42-f79f-49a8-9bf6-121696ab033f)

**Comment by davidicus** [comment]
@JordanWSmith15 This seems to be a purposeful change that we are trying to undue in order to align with spec. See [here](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2098). I have no opinions on this but by fixing one issue we are causing another. What is the preference here?
