### ISSUE TITLE
[TableViewDropdown] Custom tool tips for each Dropdown item

### ISSUE THREAD

**Issue by Happyrajsinh** [carbon-design-system/carbon-addons-iot-react#3534]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Need an option to add custom tooltips for each dropdown item. This enhancement is needed for
- IBM Engineering

**Component for which Enhancement is required:**
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-user-view-management-tableviewdropdown--with-state

### Specific timeline issues / requests

Do you want this work within a specific time period? ASAP
Is it related to an upcoming release?

### Available extra resources

What resources do you have to assist this effort?

**Comment by davidicus** [comment]
@JordanWSmith15 @dianatran18 Thoughts?

**Comment by JordanWSmith15** [comment]
@Happyrajsinh Do you have a design? My main concern is around A11Y. The native hover tooltip currently displays the label in case it doesn't fit due to translation or just being too long, and is also needed for A11Y.
<img width="328" alt="Screen Shot 2022-09-01 at 8 49 41 AM" src="https://user-images.githubusercontent.com/21066152/187918001-38528694-0c71-4703-8066-8f4df5bd831b.png">

**Comment by Happyrajsinh** [comment]
Yes we've the design, This is what it would look like:
<img width="326" alt="Screenshot 2022-08-29 at 7 16 38 PM" src="https://user-images.githubusercontent.com/79054952/187920402-5324f4f2-c520-43f9-813e-e15d867a7d33.png">

**Comment by heinsj** [comment]
This is accessible because a screen reader would read the menu item and then the hover tip. This site shows an example for Chrome Vox. https://pressbooks.library.torontomu.ca/wafd/chapter/tooltips/#:~:text=Accessible%20Tooltip%20in%20Action&text=The%20Tab%20key%20is%20used,its%20content%20is%20read%20aloud.

Following this example, our hover tips probably result in duplicate text being read each time.

**Comment by bragusa** [comment]
As long as it will work in Jaws on Firefox (our supported platform)

**Comment by Happyrajsinh** [comment]
So Team, we will need this enhancement. Anything else I can help you with?

**Comment by JordanWSmith15** [comment]
@Happyrajsinh Can you contribute this requirement, since you are the only team in need of it?

**Comment by heinsj** [comment]
My research finds that screen readers have the ability to read title attribute tooltips but this feature is often disabled by default or by the user depending on the screen reader. Rather than using the title attribute for this text, we could use the definition tooltip which is handled differently and would be more appropriate as we are providing a definition.

More info about definition tooltip: https://carbondesignsystem.com/components/tooltip/usage/#definition-tooltip

**Comment by Happyrajsinh** [comment]
No, @JordanWSmith15 I can't contribute otherwise I would have assigned it to myself right away. We don't need this on urgent basis but it can be set to medium priority.

**Comment by Happyrajsinh** [comment]
@JordanWSmith15  any update on this or estimate when this can be picked up by team?
