### ISSUE TITLE
[TimePicker] Design Audit

### ISSUE THREAD

**Issue by dianasanborn** [carbon-design-system/carbon-addons-iot-react#3566]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

There are a few tweaks I caught when working through the usage guidance and playing around with the component. 

- [ ] **1. Single focus state on time input**

Currently, the text input and icon are two different actions. Similar to the date picker, we think the time picker dropdown should open right when you focus or interact with the text input. I feel like the time picker dropdown can be missed if the user doesn't know to click on the clock icon. This will also help populate the empty text input with the right format, reducing errors on formatting. 

#### Current

Two separate triggers (one for the text input alone, one to open the time picker dropdown)
<img width="323" alt="Screen Shot 2022-09-23 at 10 24 12 AM" src="https://user-images.githubusercontent.com/43549567/191983216-07c51ce3-a10a-4d7d-b08e-eff64e8ea203.png">

<img width="304" alt="Screen Shot 2022-09-23 at 10 24 16 AM" src="https://user-images.githubusercontent.com/43549567/191983232-3f861c28-59d4-4888-9bd8-05c554452e2c.png">

#### Proposed

Have one trigger to open up the time picker dropdown automatically.
When the time picker dropdown is open, have the selected time start on the current time. Populate the text input with the current time.

<img width="402" alt="Screen Shot 2022-09-28 at 5 25 51 PM" src="https://user-images.githubusercontent.com/43549567/192891725-ef1d8ed3-4a4c-42bb-beb2-7e912e55211f.png">

- [ ] **2. Arrows are blue on hover**

The arrow icons shouldn't change color on hover.

#### Current
<img width="123" alt="Screen Shot 2022-09-23 at 10 27 57 AM" src="https://user-images.githubusercontent.com/43549567/191984717-527e4d00-5383-4262-ad68-a86c6a1ed857.png">
<img width="200" alt="Screen Shot 2022-09-23 at 10 28 04 AM" src="https://user-images.githubusercontent.com/43549567/191984730-8f84bbdb-4a1a-4f21-9c8b-0082b375ba25.png">

#### Proposed
<img width="795" alt="Screen Shot 2022-09-23 at 10 31 27 AM" src="https://user-images.githubusercontent.com/43549567/191984758-46fda0b5-e0c8-47ad-b974-7c337f6ceb19.png">

- [ ] **3. Text jumps when current state border is on**

The border should not make the text move from its position when in the current state. Refer to the focus state 

#### Current

https://user-images.githubusercontent.com/43549567/191991768-17281220-1835-4b4f-a8b9-a7feefa2f2a5.mov

#### Proposed

The current state should look like the focus state, where the text doesn't move. 

https://user-images.githubusercontent.com/43549567/191999422-cc02c7a5-55e6-484e-a1d0-58103eb4fed0.mov

**Additional update:**

Can we update the style of the "current" input to be 1px and use the `$ui-05` token color for the stroke?

You can find the update in the [design spec](https://www.figma.com/file/PeLztKjMstgRMKz5qfeRHJ/Dev-handoff-%E2%80%93%C2%A0PAL?node-id=101%3A17000&viewport=541%2C-149%2C0.25)

<img width="246" alt="Screen Shot 2022-09-28 at 5 03 25 PM" src="https://user-images.githubusercontent.com/43549567/192888272-9c0c149b-f255-4ce8-ba7f-9af5ce923754.png">

- [ ] **4. Update placeholder text to include `XM`**

After working with Robin on the content, we've decided to include `XM` in the placeholder text, so if users are typing the time format in, they will know to include AM or PM in their time selection. 

Some of the guess work will be removed once we have the time picker dropdown display when clicking on the input itself, so they see what options they have available. 

Since we also don't have a 24-hour format as of right now, the XM guidance is needed. When we work on a 24-hour picker down the road, that will only need the hh:mm.

#### Current
<img width="1126" alt="Screen Shot 2022-09-23 at 11 49 26 AM" src="https://user-images.githubusercontent.com/43549567/192001313-48e13cfb-6703-4bdf-888e-e621a3e15ae5.png">

#### Proposed

<img width="1123" alt="Screen Shot 2022-09-23 at 11 49 46 AM" src="https://user-images.githubusercontent.com/43549567/192001377-8fbce955-702d-4724-a57a-7652a44fe850.png">

- [ ] **5. Position of error and warning text for second input**

Based on pCarbon's date range picker](https://carbondesignsystem.com/components/date-picker/usage/#states), the error state text should sit under the input that has the error. Currently, the error or warning state text is displayed on the left below the first input, regardless if the error is for the start or end time input.

Carbon's examples:

Code
<img width="333" alt="Screen Shot 2022-09-23 at 12 04 10 PM" src="https://user-images.githubusercontent.com/43549567/192004595-ba6a0be1-761e-43a1-8490-8c236db56601.png">

Design (seems to be missing the icon though)
<img width="459" alt="Screen Shot 2022-09-23 at 12 04 35 PM" src="https://user-images.githubusercontent.com/43549567/192004624-27bcc11b-639e-4064-9c93-870ece6f79e1.png">

#### Current
<img width="311" alt="Screen Shot 2022-09-23 at 12 06 25 PM" src="https://user-images.githubusercontent.com/43549567/192004527-afde6eec-f5a1-4d1e-909d-d0cd98dd9ee7.png">
<img width="311" alt="Screen Shot 2022-09-23 at 12 06 30 PM" src="https://user-images.githubusercontent.com/43549567/192004672-cafb61b3-bf1d-4188-a165-9c3121f0b53d.png">

#### Proposed

 
<img width="1046" alt="Screen Shot 2022-09-23 at 12 08 27 PM" src="https://user-images.githubusercontent.com/43549567/192004828-fb9dd06e-7693-43c3-8ed5-74a2be7fb2ce.png">

- [ ] **6. Move position of AM and PM when scrolling between**

Currently the AM and PM selections just swap places. To show the scrolling behavior similar to the hour and minute picker, can we have the AM and PM move up and down in its position?

#### Current
<img width="737" alt="Screen Shot 2022-09-23 at 12 22 33 PM" src="https://user-images.githubusercontent.com/43549567/192007658-fb81c194-1264-4275-8864-680ce7ed1db4.png">

#### Propoosed
<img width="785" alt="Screen Shot 2022-09-23 at 12 22 36 PM" src="https://user-images.githubusercontent.com/43549567/192007678-500e42e7-dec0-47c2-8ee1-d1ebab105191.png">

- [ ] **7. Update selected hover state color

The current selected hover state uses the regular hover state. I'd like to change it to use the `$hover-primary` color. 

#### Current
<img width="507" alt="Screen Shot 2022-09-28 at 5 23 10 PM" src="https://user-images.githubusercontent.com/43549567/192891459-9f8a273e-b0d0-4a10-a219-ce0bf77f953d.png">

#### Proposed
<img width="505" alt="Screen Shot 2022-09-28 at 5 23 24 PM" src="https://user-images.githubusercontent.com/43549567/192891479-76c91101-2b17-4cc0-9d0f-74e23f46a4c4.png">

**Comment by davidicus** [comment]
Just a comment on this first item. 

> 1. Single focus state on time input

@dianatran18 For the first item I think the separate action is the better UX design. I am not a huge fan of automatically opening dropdown for people who may not want to use it as part of their normal workflow (ie. pasting from another document). For consistency, I imagine we should align but it could be distracting for users whose workflow do not require the dropdown. Just my two cents but understand if we must change. 

I would hesitate to automatically populate the input since this would be more disruptive for other workflows if they have to first erase or be sure to highlight the complete value before adding their input. An alternative may be to  just have the blue bar hidden and text the appropriate color until a selection is made.

**Comment by dianatran18** [comment]
> 

Hey @davidicus, spoke with the design team and Jordan on this. We all agree that the time picker should open when clicking on the text input. The user would still be able to type into the input to put in their own time, but the discovery and ease of using the time picker will enhance the user experience. The team had worked on this time picker because the Carbon time picker input was too limiting on its own to begin with.

As for the time being populated once focused on, I think it still makes sense since there is already a selected time the user is starting on. Looking at other time pickers, it seems pretty common to have a starting time selected, and then the user can adjust the time as needed. The main benefit to having it populated is that it would prevent chances of getting the time format wrong if the user were to manually type it in themselves. Even if the user were to start interacting with the time picker, the time gets populated once a number gets changed anyways, so it wouldn't make much of a difference.

**Comment by davidicus** [comment]
@dianatran18 Then why have the ability to type text at all? If we are going to auto populate the field and we are worried about wrong format then having the text field seems unnecessary. If we are trying to remain consistent with the DatePicker, then this not in line. This also does not address the workflow of those who do not want to use the spinner.

**Comment by dianatran18** [comment]
From most time picker use cases I see, the time is already populated, so there isn't even placeholder text to start off with. If we want, we can look at separating out the option of the input not being populated vs the input being pre-populated. I don't see it as a huge deal of the time being populated once open, but maybe we need to get more feedback on that. 

The date picker does allow you to type into the text field. I think it's still convenient to be able to go in and type the exact time if I need to, like I can on outlook, google, etc. 

<img width="497" alt="Screen Shot 2022-10-05 at 2 34 34 PM" src="https://user-images.githubusercontent.com/43549567/194138741-ead3bdfe-56b5-4a4b-817d-86bb8b2927c0.png">
<img width="585" alt="Screen Shot 2022-10-05 at 2 34 50 PM" src="https://user-images.githubusercontent.com/43549567/194138760-672bc4ae-dbbd-4584-b435-1c6656eae648.png">

The purpose of this time picker is to add the functionality of the spinner, because Carbon has a simple input without a spinner but it wasn't sufficient for what the team needed. If we keep the text input editable, then it gives you best of both worlds. Also, if there are use cases where you might not want to use the spinner and just have the text input, we recommend teams just use the Carbon time picker, not this extension of it.
