### ISSUE TITLE
[Table] callback issues when single select with Radio buttons props are set

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3616]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

There are two defects surrounding the single select behavior with radio buttons.

1. On line 252 of `TableBodyRow.jsx` we are calling `onRowSelected` inside an `onChange` event for the `TableCell`. We are also calling the `onRowSelected` when the `RadioButto` element is clicked on line 265. We should only be calling this once. 
You can see this in our storybook [here](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground). Make sure `options.hasRowSelection` is set to 'single' and the `options.useRadioButtonSingleSelect` options is clicked in the 'Selections and actions' knob tab. Then open the actions panel and click on the radio button. You will see the callback fired twice. 
2. With the same story and knobs active try clicking on the row in an area outside of the radio button cell with the actions tab open. You will see that an `onRowSelected` and an `onRowClicked` callback are fired. Notice that the radio button does not show a selected state. This most likely stems to when we added the radio buttons for single selection. Previously, a user could click anywhere and it would select the row. @JordanWSmith15 @dianatran18 can you chime in with whether we should continue to allow the clicking on a row to fire the `onRowSelected` and update the radio button accordingly or  disallow row clicks to fire the `onRowSelected` when we are using radio buttons? 

@JordanWSmith15 This is related to the defect being worked by Tom for Graphite. 

### To Reproduce

1. Go to [this](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground) story
4. Got to the 'Selections and actions' knob tab in the knob pannel.
5. Make sure `options.hasRowSelection` is set to 'single' and the `options.useRadioButtonSingleSelect` options is clicked
6. Open the actions panel
7. Click on the radio button in the table
8. See the action firing twice.
9. Click anywhere in the row and see the `onRowSelected` callback being fired. 

We will want to make sure that our behavior for single select without the radio buttons and the multi-select functionality is preserved.

**Comment by dianatran18** [comment]
I would follow what [Carbon's radio button selection](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--with-radio-selection) does, and only have it on the radio button, not the full row. 
I feel like selecting the full row can conflict with other potential actions on the row too, like inline row actions, links, etc. 

Also, note that Carbon's also has a selected row state but ours does not. Was that intentional? For consistency with other selected state use cases, we should add that back in. I actually realized we don't have selected states for the checkbox variant too. We have that in our [designs](https://pages.github.ibm.com/ai-applications/design/components/datatable/rowactions#batch-actions) along with [Carbon](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--with-selection-and-sorting), so we'll need to align on that too.
