### ISSUE TITLE
[Storybook] Re-evaluate documentation of components with >10 stories

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#771]
### Summary

Each story for a component is intended to represent [a single visual state of that component](https://storybook.js.org/docs/basics/writing-stories/). With complex components (`Table`) or components with many variants (`TimeSeriesCard`, `ValueCard`, etc.), the growing story list is difficult to navigate.

Atop this cognitive load, we also have `Stateful` stories that provide a stateful (interactive) example of the component. Some have multiple stateful examples, further clouding understanding.

#### Some ideas to remedy:
- [ ] Add documentation to the welcome story restating storybook's intention - each story represents a single visual state of a component, noting the exception of `Stateful` interactive stories. This distinction of `static` vs `interactive` is currently not clear for users not familiar with storybook.
- [ ] Build a list of crucial/important/essential stories for each component with >10 stories. This core set can still be more than 10, we're just trying to cut back from huge numbers like 30 😳 .
- [ ] Refactor to remove the non-essential stories - replace these with well crafted `enzyme`/`@testing-library/react` tests looking at props, event handlers, etc. to cover the functionality previously covered by storyshots.
- [ ] If a component has multiple stateful stories, combine these together into one stateful component with the most common use case. We may be able to enable further configuration via knobs to turn off different feature sets within a component.
- [ ] Standardize story names. A common format we could follow is "with {feature}". Stateful stories should always have the same format. Commonly we've used "Stateful{Component} Example", minor point of clarity could be an additional space "Stateful {Component} Example"
- [ ] Improve documentation of complex components via a readme for that component. We may find a link to a codesandbox.io helpful to provide a playground environment.

Are there other ways we could improve this?

<sub>[Internal tracking issue 81](https://github.ibm.com/Watson-IoT/pal-tracking/issues/81)</sub>

**Comment by davidicus** [comment]
I like the readme for each component. Carbon does this and it helps to layout  how each of the building blocks that make up that component work together. This is also a great place to give examples of what certain data payload that are passed in as props would look like.

**Comment by tay1orjones** [comment]
Agree. That can also eventually flow into [Storybook Docs](https://github.com/storybookjs/storybook/tree/master/addons/docs), too. They've been improving the .MDX support in the recent minor beta version.

Instead of using the auto-generated content for these complex components, we can customize it ourselves to ensure it's formatted for understanding. I anticipate the auto-gen content to not be the best for certain cases, particularly with how large some of our prop tables can be.

**Comment by sstone2423** [comment]
These look like good remedies. Table is up to ~40 stories with the latest PR which is just crazy.

It would be great to get a fine definition of what a story is meant to do. It seems that some stories are there purely for testing, which would be fixed by converting them to tests as you said @tay1orjones .

The library could get cut down if we cut out stories for subcomponents that aren't meant to be used outside of the parent component. For example: https://carbon-addons-iot-react.com/?path=/story/watson-iot-tablebodyrow--normal

**Comment by tay1orjones** [comment]
> This distinction of `static` vs `interactive` is currently not clear for users not familiar with storybook.

Was reminded of this today as someone brought this to my attention again. I think we might be able to help make this distinction via `addon-docs` in #963 

Fully interactive component demos can be made available in the .mdx `docs` tab, or even in a standalone documentation story. Then the stories can serve their intended purpose of being static, individual slices of functionality.

**Comment by bjornalm** [comment]
Great initiative. We should also make sure that we have a solution for viewing the source code of the stateful stories, this is not working with our current setup.

**Comment by stuckless** [comment]
For me the reason to combine the stories and use knobs is that `static` stories is not how components are used, and if it was, then, you can simply enable the single property.  Because of this, it poses some challenges.

1. If I have component with 5 properties, then I need ~30 stories statically exercise all combinations of just 1 component.  As a result, no one creates those combindations, and then they can't be tested visually.
2. Most issues that I find with components come from the fact that a new property X causes a side effect when used with property Y.  Because of #1 there's no way to tell that, so when reporting a bug it takes a huge amount of effort to simply show that X and Y are causing side effects.
3. Components need to react properly to changes in properties.  Static stories will not show this, and during development devs will sometimes not notice it especially when managing state in a component.  Like #2 it becomes difficult to report these issues because you need to build the interactive story in order to show it.

So for me, if storybook is a developer tool to help us better build and test how components react, or if it's a tool for showing how to use a component, then static stories seems to miss the mark on both counts.

Personally, I don't get the need for a story that simply shows component A with X prop set, and then another story to show component A with the X prop unset, and then repeat this for N number of props, individually.  It's not indicative of a real use of the component.  Components are going to be used with multiple properties set, and we can't control with props are going to set in combinations, and those props are likely going to come from stateful sources and the component needs to react those changes, and as such, static stories really don't offer much aid to the developer or user of the component.
